# Hipscat config to DP0
#  The idea of yaml is to provide configuration parameters for hipscat.
# Each key must be a valid argument to the ImportArguments class.
# https://hipscat-import.readthedocs.io/en/latest/autoapi/hipscat_import/catalog/arguments/index.html#hipscat_import.catalog.arguments.ImportArguments

sort_columns: objectId
ra_column: coord_ra
dec_column: coord_dec
# input_path: /lustre/t1/tmp/singulani/import_hipscat/inputs/DP02
input_path: /lustre/t1/tmp/singulani/pz-compute/scheduler_examples/slurm/rail-slurm-preprocess/outputs/
input_format: parquet
output_artifact_name: DP02
output_path: /lustre/t1/tmp/singulani/import_hipscat/outputs
dask_tmp: /lustre/t1/tmp/singulani/import_hipscat/tmp
dask_n_workers: 10
dask_threads_per_worker: 56
overwrite: true
resume: true
