# Hipscat config to DR2
#  The idea of yaml is to provide configuration parameters for hipscat.
# Each key must be a valid argument to the ImportArguments class.
# https://hipscat-import.readthedocs.io/en/latest/autoapi/hipscat_import/catalog/arguments/index.html#hipscat_import.catalog.arguments.ImportArguments

sort_columns: COADD_OBJECT_ID
ra_column: RA
dec_column: DEC
input_path: /lustre/t1/cl/des/Y6A2_GOLD/cats/
input_format: fits
output_artifact_name: DR2_FITS
output_path: /lustre/t1/tmp/singulani/import_hipscat/outputs
dask_tmp: /lustre/t1/tmp/singulani/import_hipscat/tmp
dask_n_workers: 10
dask_threads_per_worker: 56
overwrite: true
resume: true
